### ISSUE TITLE
How can i use engine on win10

### ISSUE THREAD

**Issue by Emirhantaze** [matt77hias/MAGE#70]

**Comment by matt77hias** [comment]
"Using" as in compiling the engine/running the demo project?

Just check out the provided Visual Studio solution file: MAGE/MAGE.sln

**Comment by Emirhantaze** [comment]
Thanks and also i want to use it for decoding scx for translating Steing;gate 0

**Comment by matt77hias** [comment]
MAGE is currently a one-man's project that is far from complete. I am mostly occupied with the game engine foundation layers including core components such as rendering. The architecture at this point in time is quite volatile and can and will be changed fundamentally in the near future, breaking other layers on top of these. Therefore, the scripting system (which is at a higher level) is minimally for the time being. This also means that language support for dialogues is unfortunately not one of the current priorities for the near future and iterations.
